url: "https://mochimilk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "Segoe-Variable/" # the subpath of your site, e.g. /blog
title: "Segoe Variable" # the name of your site, e.g. ACME Corp.
